source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

inhibit_all_warnings!

install! 'cocoapods',
	:deterministic_uuids => false

target :CreationMatrix do
	pod 'BRCybertron',          :path => '../'
	pod 'JSONSyntaxHighlight'
end
